# Generated by Django 5.2.5 on 2025-09-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='description',
            field=models.TextField(default='Delicious Chai'),
        ),
        migrations.AddField(
            model_name='chaivarity',
            name='price',
            field=models.FloatField(default=20.0),
        ),
    ]
